### ISSUE TITLE
CFD and CSM tests for case setup

### ISSUE THREAD

**Issue by ldlcour** [pyfsi/coconut#10]
To make it easier for (new) users to get their case up and running, I thought it would be interesting to provide the possibility of testing the involved solvers separately, as was possible in Tango. 

After a discussion on the implementation with @ldmoerlo, @nicolasdlss, @toondm we thought about doing this as outlined hereunder (correct me if I made a mistake or forgot something). 

**The idea is:**
- This is a case-oriented test and not directly intended to test the code of the SolverWrapper. Rather it should test the setup of the user-provided files and settings 
- The testing of one solver should not rely on the other solver
- The testing should be easy and clear to set up 
- Required alterations to the .json-file should be minimal and not interfere with the settings that are used for running the complete simulation
- Preferably the testing does not require alterations to the SolverWrapper codes

**What is tested?**
- If the solver receives correctly formatted input from CoCoNuT then it will run and produce output 

**The suggested implementation is:**
- Define a new coupled_solver for testing a single solver (e.g. test_single_solver)
- A normal coupled_solver requires "settings" in the .json file. The test_single_solver will require "test_settings" and will also be able to read from "settings"
- The basic testing happens by providing input files with 0-displacement for the flow solvers and 0 loads for the structural solvers 
- Add the possibility of performing slightly more advanced testing by defining python functions that return load or displacement based on x, y, z of the node/loadpoint and possibly time (test-function)
- The "test_settings" will need to define what solver needs to be tested (and possibly later on an identifier for the function that the user wants to apply as test-function)
- For mapped solvers only the deepest level will be tested and not the mapping itself

**Comment by joris13** [comment]
Good idea. I would only comment on the last item: I think it should/will be invisible for the test whether he is testing a real solver or a mapped solver, as both are solvers for what the coupling concerns.

**Comment by nicolasdlss** [comment]
Maybe it is an idea to make it optional whether or not to include the mapping, as I think it might be useful to be able to each solverwrapper without mapping as well. This can be a simple boolean which, when True, looks for the "deeper" solverwrapper if the type is `mapped`.

**Comment by ldlcour** [comment]
Correct me if I'm wrong but if we want to be able to test mapped solvers (including the mapping) does that not imply that when using the test we need a field to map from and to, which is typically obtained from the other solver, which would make the testing of solver-1 dependent on solver-0?

**Comment by nicolasdlss** [comment]
To initialize the mappers you indeed need interfaces on both sides, so that would mean you need either the interface from the other solver or you would need to define one yourself, which might be not so straightforward. So in light of this I think it indeed best to focus on the solver alone. Maybe in the future mapper testing could be added.

**Comment by ldlcour** [comment]
I have updated the branch "Implementation_CSM_Test" which should cover this issue. 
The name might be slightly misleading as the code also works for testing the CFD.

Before filing a pull-request it might be interesting to get this tested by some of you and discuss. 

 - The main code can be found in coupled_solvers/test_single_solver.py 
 - A test example can be found in test_examples/testing_testCSM
 - Compared to a case that you would actually run the following has to change in order to test a single solver:
         - the type of the coupled solver has to be set to coupled_solvers.test_single_solver
         - apart from "settings" which you can just keep the same as for the real case the test_single_solver requires "test_settings"
         - these "test_settings" must contain a solver_index referring to the solver to be tested
         - test_settings can be used to overwrite parameters in settings for testing purposes e.g. delta_t
         - mapping is currently not checked as this requires information from the other solver as well. Such an option could be added later on with e.g. a parameter "check_mapping"
         - If present in the working directory the file test_function.py will be imported
         - If this file is not present then a 0-input will be used for testing
         - Similarly setting the parameter "test_class" to "None" will default to a 0-input

If the user wants to supply an input via simple functions they can do so with by including a file named "test_function.py" in the working directory:
    - This file can contain several classes for different test scenarios.
    - The name of the class to be used for testing is specified in the parameter file 
    - Depending on the variables of the input interface for the tested solverwrapper (PRESSURE, TRACTION, DISPLACEMENT) the class needs to contain functions with the name (calculate_PRESSURE, calculate_TRACTION, calculate_DISPLACEMENT)
    - It would be best to base the test_function.py on a provided example

Apart from testing whether settings for a solverwrapper and the setup of the case are "correct". The testing also allows to evaluate for example mesh deformation with imposed displacement and could be useful for one-way FSI simulations.
