### ISSUE TITLE
Abaqus: Speed-up usrInit.f

### ISSUE THREAD

**Issue by hdolfen** [pyfsi/coconut#109]
For some cases *`USRInit.f`* takes quite a while. I propose some steps to make it faster and run it less often:

- [x] Don't run it if `timestep_start` is not `0` (omit check of *`...Elements.dat`*.
- [x] Currently two files are written by the user subroutine: *`...Faces.dat`* and *`...FacesBis.dat`*. In Tango they were compared to each other but this test is not expected to fail. UTRACLOAD and DLOAD are responsible for the two files and are both required. I think just omitting the I/O operation in one of those can already be a speed-up (so it should just return F = 0). I would not delete it, but put it in a big conditional that can be set on `TRUE` in case `self.debug` is `True` in the solver wrapper code.

Things that also can be done but I suggest leaving like it is for now because the programming is quite involved:

- Parallelize it (difficult because of the file that has to be written).
- It currently does multiple loops: detect when the second loop is started and abort. Currently it aborts when the increment increases (`KINC > 1`) which helps in cases with subcycling. However even in this first increment it seems to loop 2 times over the load integration points. It could be based on the element number `NOEL`, but the variable keeping track has to be a global variable (like those defined at the top of the file under `BLOCK DATA`), such that it can be accessed upon a next function call (i.e. next load integration point). Another caveat is the possible presence of multiple `ModelParts`, in which this detection of the second loop happens for a different `NOEL`.

**Comment by hdolfen** [comment]
This if-clause could even be a compiler directive, like it is currently done for the ramp setting in *`USR.f`*.

**Comment by awbral** [comment]
I am not too fond of the first suggestion. The *`USRInit.f`* makes sure the mesh information from the *`.inp`* file gets passed on to CoCoNuT. If you skip the *`USRInit.f`* upon restart, there is a possibility that a simulation is attempted with a different mesh (e.g. coarsening/refinement) without that CoCoNuT knows about it, which probably gives weird results without any clear indication. Therefore, I would rather keep the check of the *`...Elements.dat`* file in the initialization.

**Comment by hdolfen** [comment]
I would enforce using the same mesh differently (without needing a check), by putting the following lines:
https://github.com/pyfsi/coconut/blob/b463679a87a695a0c0dddbb68d97b846ce51697f/coupling_components/solver_wrappers/abaqus/v614.py#L77-L79
in an if-clause, such that the .inp files only are generated for a new case. For a restart, the same files are used, hence the same mesh.

**Comment by nicolasdlss** [comment]
From the CoCoNuT meeting of 5/7:
Problem that DLOAD and UTRACLOAD both output the same data, is most urgent.
