### ISSUE TITLE
what the ml command does

### ISSUE THREAD

**Issue by lixiaole2017** [pyfsi/coconut#128]
Hello everyone,  what the ml command does？Thank you.
like "ml ANSYS_CFD/2019R3"
PS I want to run it on windows10.

**Comment by joris13** [comment]
ml is "module load", basically loading the configuration for a certain solver.

CoCoNuT only has been tested on Linux and that will stay this way for the foreseeable future. The Python code is probably relatively portable to other operating systems, but the solver wrappers will require extensive rework. So, I think you would have to spend a lot of time to get it working on Windows. This is not something we can/will support.
