### ISSUE TITLE
Remove X, Y, Z attributes from Nodes. 

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#15]
We recently discussed the usefulness of the X, Y, Z attributes in de Nodes objects. 
It seems that these are only used in the Fluent solver wrapper, and that even there they can easily be removed.
The conclusion was therefore that we should remove them from all CoCoNuT code, to avoid confusion and outdated info. 

Some more thoughts about the Node coordinates:
- We use X0, Y0, Z0 to store the original coordinates. These are used everywhere (e.g. mappers). We could rename them to X, Y, Z  as we only store one set of coordinates, but I would not do that so that it is always clear that these are the original coordinates from timestep 0. 
- X0, Y0 and Z0 may never be changed (nor the Id of the Node for that matter). Should we somehow protect them, so that they can only be changed during creation of the Node? Constant attributes don't exist in Python, but [this post](https://stackoverflow.com/questions/10929004/how-to-restrict-setting-an-attribute-outside-of-constructor) gives some good alternatives. 
- For visualization (post-processing) it can be interesting to plot the deformed geometry. We could then create X, Y, Z automatically during export (to VTK for example) if the Variable "displacements" is available in the ModelPart. That way the X, Y, Z coordinates are definitely up to date, which is currently not always the case.

**Comment by nicolasdlss** [comment]
- Fully agree on keeping the zero
- Protecting the values of X0, Y0, Z0 and the ids is definitely safer, but I don't think that it is really a problem if they are not protected.
- Honestly, I don't fully get what you mean, but that's probably me. Two thoughts come to mind.
First, creating X, Y, Z during export only makes sense if they are used someplace else, but I don't see where they could be useful. After all, if the Variable DISPLACEMENT is present, that information is already accessible there. I never used VTK before, but I imagine it requires the coordinate data to be stored in a specific format. Creating X, Y, Z, feels like an unnecessary extra step.
Second, visualization is definitely useful, but we should keep in mind that the used solvers often already have quite some post-processing functionality. Nevertheless, the branch plot-tool (waiting for approval ;) ) already implements plotting the displacement, but that's a discussion for another issue thread.

**Comment by navaneethkn** [comment]
@nicolasdlss I am working on vtk visualization for Kratos as it doesn't come with its own free post-processing unit. I think it will be useful if I extend the capability to coconut to visualize interfaces that are created in each solver wrapper for debugging purposes. We don't have to create X, Y and Z explicitly. We can also visualize the model parts in interfaces and their field values in the original coordinates.

**Comment by toondm** [comment]
About the third point: true, not much sense in creating X, Y, Z as that info is available in "displacement". 
I think the advantage of having visualization with e.g. Paraview based on vtk files, is that you can easily scroll through Interface data for different iterations or timesteps, something Fluent can't do. 
About the plot-tool, I know it's waiting for review, just didn't get to it yet, sorry!

**Comment by nicolasdlss** [comment]
Sure, I also think it visualization is very useful. I just wanted to point out, that we should keep the effort we put into it proportional to its purpose, that's all :). Also, I think we should keep the distinction clear between code debugging and post-processing (with the aim of presenting results). But on the how and the why we can discuss in the other thread.
@toondm no problem, was more like a gentle reminder

**Comment by hdolfen** [comment]
I think this issue can be closed as soon as executing the following command in the coconut directory does not yield any results.
`grep -r 'node\.[XYZ][^0]' ./*`
Now this is still the case for the OpenFOAM tests.

**Comment by hdolfen** [comment]
This issue can be closed, pull request #111 removed the last references to these objects (in comments). It was tested by running `grep -r 'node\.[XYZ][^0]' ./*` in the coconut directory.
