### ISSUE TITLE
Hardcoded Variables in solver wrappers.

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#16]
The solver wrappers can currently only deal with a small number of Variables, namely the ones used in FSI: pressure, traction and displacement. 
In the JSON file however, you can give whatever Variables you like to the Interfaces. This will eventually lead to an runtime error, but probably not a very clear one. 

As a solution, we discussed about hardcoding Variables in the current solver wrappers (they can't handle any others anyways), and adding a check in the solver wrapper to see if the Interfaces have the expected Variables. That way the error thrown on runtime would clearly indicate if a wrong Variable is used.

**Comment by hdolfen** [comment]
Have we discussed this already in real-life? I think it would be a good solution.

**Comment by nicolasdlss** [comment]
From the CoCoNuT meeting of 5/7:
The variables are left in the parameter file for clarity and allowing for changes in the future (e.g. leaving out traction).
However, an error should be thrown when wrong variables are set in the parameter file.

**Comment by nicolasdlss** [comment]
Proposal for @VictorVanRiet
