### ISSUE TITLE
Use $TMPDIR instead of hard coding /tmp

### ISSUE THREAD

**Issue by stevenvdb** [pyfsi/coconut#163]
On some clusters (such as the KU Leuven VSC cluster) the /tmp directory is not intended for large files. Instead, the directory stored in $TMPDIR (which points to dedicated space on a local disk and is set when a job starts) should be used. Most Unix programs follow this convention (https://en.wikipedia.org/wiki/TMPDIR), but here /tmp is hard coded in some places, for example https://github.com/pyfsi/coconut/blob/8a88130e089ce9094114e8ad07f1acae95c8a388/coupling_components/solver_wrappers/fluent/v2019R1.c#L501)
Would you consider changing this behavior and use ${TMPDIR} for storing such files if the variable is set?

**Comment by hdolfen** [comment]
Thanks for pointing out this flaw in our code, the issue has been addressed in pull request #161. The code now uses $TMPDIR unless it is unset, then still /tmp is used.
