### ISSUE TITLE
No warning is given when setting dynamic mesh fails, simulation keeps running

### ISSUE THREAD

**Issue by NPynaert** [pyfsi/coconut#170]
Raise Error

**Comment by nicolasdlss** [comment]
What do you mean exactly with "setting dynamic mesh"?

**Comment by NPynaert** [comment]
The FSI interface needs a dynamic mesh setting in fluent. This is taken care of by CoCoNuT.

**Comment by NPynaert** [comment]
Difficult to assess when setting the dynamic mesh fails.
