### ISSUE TITLE
CoCoNuT should stop when Fluent has license error

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#173]
Currently, CoCoNuT doesn't stop when Fluent has a license problem.
In order to kill CoCoNuT, it should check whether the Fluent process still exists at certain time intervals (10 minutes or so).
If the Fluent process no longer exists, an error should be raised.

**Comment by hdolfen** [comment]
Any proposals? Should we create an optional argument in the `CocoMessages.wait_message()` function to pass the process object returned by `subprocess.Popen` and poll this object every so often?
