### ISSUE TITLE
Abaqus crashes when to many cores are asked.

### ISSUE THREAD

**Issue by NPynaert** [pyfsi/coconut#174]
### Time step 1, iteration 1 ###
Abaqus Error: The number of cpus (39) exceeds the number of cpus available (36).
Abaqus/Analysis exited with error(s).

**Comment by hdolfen** [comment]
I think this is desired behavior. The error is clear and it makes no sense to ask more cores than there are cores available. Therefore I propose not to change anything.

**Comment by NPynaert** [comment]
In fluent when more cores are asked than available, the amount of cores that are available are taken and a warning message is printed. The simulation does not crash.

But I agree that the error is clear. Just for my case, I had to wait a long time until this error pops up in the abaqus.log file.
