### ISSUE TITLE
Example breaking_dam_fluent2d_abaqus2d does not work with Fluent versions newer than 2020R1

### ISSUE THREAD

**Issue by NPynaert** [pyfsi/coconut#183]
Multi-phase does not work with newer Fluent versions. This is due to the fact that the summary file acquired from fluent has a different layout in the new versions, such that the parsing is not done correctly.

**Comment by BastiLoe** [comment]
For carity, please state up to which FLuent-versions it is working and which are currently not working. Thanks.
