### ISSUE TITLE
When running examples openfoam3d_abaqus3d ,the occupation of cpu too small ,What is the problem

### ISSUE THREAD

**Issue by SYH711** [pyfsi/coconut#192]
Hope for you answer

**Comment by hdolfen** [comment]
How to set the desired number of cores used is described in the documentation.
For Abaqus: https://pyfsi.github.io/coconut/abaqus.html#mandatory
For OpenFOAM: https://pyfsi.github.io/coconut/openfoam.html#parameters

Hope it helps.
