### ISSUE TITLE
The ReadMe.md contains a typo; there is no folder "coconut/examples/tube_tube_flow_tube_structure/"

### ISSUE THREAD

**Issue by jellepoland** [pyfsi/coconut#224]
In the 1D first example case, one is requested to open a folder using:
`cd $COCO/coconut/examples/tube_tube_flow_tube_structure/`

It should instead be (replacing underscore with backslash):
`cd $COCO/coconut/examples/tube/tube_flow_tube_structure/`

**Comment by nicolasdlss** [comment]
Thank you for noticing! The typo has been fixed with commit [1585931](https://github.com/pyfsi/coconut/commit/15859315531be7b07f947b6acc18e86985daf818).
