### ISSUE TITLE
Multinode does not work for Fluent 2024R1 (UGent HPC issue)

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#244]
For earlier Fluent versions, an Intel module had to be loaded in _`solver_modules.py`_ to work multicore (and multinode).
For Fluent 2024R1, this is not needed to run multicore, but is needed to run multinode.
However, the most recent available intel modules on the HPC conflict with Fluent 2024R1.

**Comment by NPynaert** [comment]
Reinstallation of the FLUENT/2024R1 version on the HPC resolved this issue.
