### ISSUE TITLE
Could OpenFOAM-v2406 couple with Abaqus through coconut?

### ISSUE THREAD

**Issue by QB-Lin** [pyfsi/coconut#251]
Could OpenFOAM-v2406 couple with Abaqus through coconut?
There was description of coupling with OpenFOAM v11 (org version) in the document of COCONUT
I hope to couple Abaqus with OpenFOAM (com version)

**Comment by nicolasdlss** [comment]
The only component missing to do this, is a solver wrapper for the openfoam.com (ESI) variant.
This solver wrapper would be very similar to those for the openfoam.org (Foundation) variant which are already present.
There is currently a PhD student who started working on writing this solver wrapper (for version v2312, but this would be virtually the same for OpenFOAM-v2406).
Of course you can also create this solver wrapper yourself.
