### ISSUE TITLE
Python tube solver tests executable files

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#28]
When downloading CoCoNuT as a zip file, the tests of the python solvers don't work, because the execution rights of some files are not copied.
The tests for the python solvers have to be updated, to work even when the installation is done using zip of the files.

**Comment by nicolasdlss** [comment]
This problem occurs when the zip-file is unpacked using Windows. If unpacked in Linux the files have the correct permissions. Therefore, I suggest to add explicitly to the user guide that unpacking has to be done in a linux environment.

**Comment by toondm** [comment]
I added this to the documentation.
