### ISSUE TITLE
Save_result has to be put on "false" after restart in OpenFOAM wrapper

### ISSUE THREAD

**Issue by mvervaec** [pyfsi/coconut#31]
Restart is not compatible with "save_results". This means for a restart, save_results has to be set on "false" before restart can be done.

**Comment by nicolasdlss** [comment]
I have implemented a small fix for this issue. When a restart is done a new 'results.pickle' file is made. So a previous one is not looked for nor extended.
To avoid mistakingly overwritting it, it will create a 'resultsX.pickle' with X the latest number that does not exist, e.g. 'results1.pickle'. This also works with an own case name.
