### ISSUE TITLE
Convergence_criterion structure

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#4]
Multiple convergence criteria are now specified using `convergence_criteria.or` or `convergence_criteria.and`. The key `settings` refers to a dictionary of the different criteria with used keys `convergence_criterion0`, `convergence_criterion1`, etc. : 
```
 "convergence_criterion" :
        {
            "type" : "convergence_criteria.or",
            "settings" :
            {
                "convergence_criterion0" :
                {
                    "type": "convergence_criteria.iteration_limit",
                    "settings":
                    {
                        "maximum": 20
                    }
                },
                "convergence_criterion1" :
                {
                    "type" : "convergence_criteria.relative_norm",
                    "settings" :
                    {
                        "tolerance" : 1e-6,
                        "order" : 2
                    }
                }
            }
        }
```
A minor adjustment, is to change the dictionary corresponding to the key `settings` to a list, in the same way as is done with the solver wrappers and mappers. In my opinion that would increase the uniformity and the effort is minimal.
```
 "convergence_criterion" :
        {
            "type" : "convergence_criteria.or",
            "settings" :
            [
                {
                    "type": "convergence_criteria.iteration_limit",
                    "settings":
                    {
                        "maximum": 20
                    }
                },
                {
                    "type" : "convergence_criteria.relative_norm",
                    "settings" :
                    {
                        "tolerance" : 1e-6,
                        "order" : 2
                    }
                }
            ]
        }
```

**Comment by joris13** [comment]
I would argue the opposite, given that the other settings are not lists. Otherwise user has to remember where to use list for settings and where not. Also then the criteria do not have a name and cannot be addressed uniquely.

**Comment by nicolasdlss** [comment]
As counter argument: 
Lists are already used in the `mapper combined` object to list the mappers which are combined and also the solverwrappers are given as a list, so from my point of view, whenever an enumeration is made, a list is currently used. 
Secondly, they can be addressed uniquely by there position in the list using an index (convergence_criterion[0]), in the same way as this done for the solver wrappers. But, personally I don't seed a need to address convergence criteria uniquely as their order has no effect.

**Comment by joris13** [comment]
Ok, I understand. Then list when enumeration is made. Good that items can still be identified uniquely.

**Comment by navaneethkn** [comment]
I agree with Nicolas to use the use of a list whenever there are multiple components involved. Also, we don't need keys because we are anyway appending all the criteria in a list, which is subsequently used in `IsSatisfied()`. However, I agree with Joris's objection to using the list in the `settings` option because it is not standard. Therefore, I suggest replacing `settings` with `criteria_list` or something similar.

**Comment by joris13** [comment]
I would not replace settings by criteria_list, but put the list inside settings:

settings
{
                criteria_list
                [
                                {
                                                …
}
{
                …
}
]
}

This ensures consistency for settings and enables the use of a list…

**Comment by navaneethkn** [comment]
Ok. Sounds good to me.

**Comment by awbral** [comment]
Pull request (#26) submitted. Adapted structure that Joris proposed.
