### ISSUE TITLE
Docs test_single_solver

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#40]
The test_single_solver is a coupled_solver that can be used to test the single-physics solvers separately. This is very useful, e.g. for debugging Fluent and Abaqus test-cases before running the full FSI simulation. Currently, users have an example case of the test_single_solver to base their code on, but there is no documentation yet. 

So: documentation must be made for the test_single_solver, to detail how it works, and what all the possible options are.

**Comment by nicolasdlss** [comment]
Now the function providing dummy data is called `test_function.py`. To avoid confusion, to make it more pythonic and to be able to run in the gui, I would suggest to change the name of the file such that it no longer starts with test.

**Comment by toondm** [comment]
Good point, it shouldn't have the same name as a unit-test file. 

What do you mean with running in the GUI @nicolasdlss ?

**Comment by awbral** [comment]
I changed its name to `functions.py`, hope this works for you? Follow updates in the documentation_test_single_solver branch.

**Comment by nicolasdlss** [comment]
@toondm Probably there is a workaround, but in Pycharm if you want to run a script which starts with `test`, it automatically runs it using pytest. Just a detail as another reason why the name should change.

@awbral Maybe `functions.py` is a little to generic. It is good practice, to let the name clearly state what the function is/does, so as long as we are changing the name, maybe we could go for `dummy_solver.py`? What do you think?
I will also make some small changes to the code (I noticed some small issues and also the printing at the end fails), but in a new branch maybe.

**Comment by awbral** [comment]
yes, I noticed the fail too, wanted to look into that. 

`dummy_solver.py` is actually a pretty good name! Maybe I can change that now? You could make a new branch, but then also change the name of `test_function.py` in `test_single_solver.py`, or continue in the branch I'm working on?

**Comment by nicolasdlss** [comment]
I will do it in a separate branch, to let the name of the branch reflect its purpose. And will pull in your branch, maybe after merging it with the master? Or do you still have a lot of work before you can merge?

**Comment by awbral** [comment]
At this point, the documentation file of the example "test_single_solvers" has the same name as the documentation about this functionality itself, namely 'test_single_solvers.md'. Shouldn't this change in order to be able to render properly?

**Comment by toondm** [comment]
Yes, that is one of the requirements of mkdocs: all MD files ***must*** have different names. 
The underlying reason is that all MD files are converted to file index.html, located in a folder of the given name. All these folder are at the same level of the static HTML website as you can see in the [gh-pages branch](https://github.com/pyfsi/coconut/tree/gh-pages).
I think run_mkdocs.py gives an error if you try to build the website this way.

**Comment by nicolasdlss** [comment]
To be conform with documentation structure used up to now, the documentation on the single solver, should be part of the `coupled_solvers.md` file. Next to that there should be a `test_single_solver.md` file in the corresponding example folder. In this way, there are no files with identical names. 
I will try to have a look a the pull request later today.
