### ISSUE TITLE
Additional example cases

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#41]
Currently the example cases are limited to variations of the tube (1D, 2D, 3D, mixed...). 
I think it would be useful to have a few more example cases (although not necessarily as many as Tango has), so that the user has some more variation as inspiration. E.g. an example where the Interface consists of several ModelParts would be nice. 
Also, I don't think an example should work with each version of the software (e.g. different Fluent versions), because that would be too hard to maintain, and would lead to too much code.

**Comment by nicolasdlss** [comment]
Perhaps, the flexible beam can be an interesting test case. It is an often used test case for FSI, much like the flexible tube.

![image](https://user-images.githubusercontent.com/56599042/100200045-5e15f400-2efe-11eb-8d44-eecb6838db2a.png)
(image from Degroote, Joris et al. “Performance of Partitioned Procedures in Fluid-structure Interaction.” COMPUTERS & STRUCTURES 88.7-8 (2010): 446–457. Print.)

**Comment by joris13** [comment]
Mmm, FSI2 and FSI3 of the flexible beam are very time consuming test cases because a lot of periods are required to reach regime. The FSI1 case is steady but with very small deformation (nothing like the figure). This can be a fast test.

**Comment by toondm** [comment]
Even if they are time-consuming, it might be interesting to put such a well-known benchmarking case in our code, no? 
If we can get accurate results with different solver combinations (e.g. Fluent-Abaqus, OF-Kratos), that could be a good proof of the capabilities of coconut, for outsiders.
