### ISSUE TITLE
Abaqus wrapper: incrementation setting

### ISSUE THREAD

**Issue by hdolfen** [pyfsi/coconut#42]
A part of the code where many errors originate from is the `write_start_and_restart_inp` method. This method reads an Abaqus input file (.inp) and creates two new input files: one called `CSM_timeX` for the first time step X+1 and one called CSM_Restart for all subsequent time steps.

In the original input file, the incrementation settings are substituted using the settings in the JSON-file (`delta_t` and if `subcycling` is enabled also `minInc`, `initialInc`, `maxNumInc` and `maxInc`). It does this substitution by looking for keywords in the input file. The incrementation information is searched for by searching for the line containing the word `*dynamic` or `*static`. In case of `*dynamic` (unsteady cases), it also looks for the word `application` on the same line, checking the type. There some issues arise:

1. Currently `application` is only allowed to be `quasi-static` or `moderate dissipation`, for anything else an `NotImplementedError` is raised (in `614.py`).
2. Abaqus users who prefer the GUI and use default settings in their step definition end up with an input file not containing the word `application`. The code can currently not deal with that and raises an error that is hard to interpret.
3. This makes the code rather rigid, Abaqus users who want to use a different application have to adapt this part of the code to accept their input files as well.

I think we should discuss what is a desirable solution to make the code less rigid but more user-friendly. I think of following options:

1. Keep it, but make it robust against the second issue (e.g. by assuming default values) or mention in the documentation that no default value may be used for the application. It is also possible to omit the check of the application. Then the third issue is still there, which we should either accept or try to implement all possible Abaqus set-ups (which is hard to predict and makes the code very long).
2. Keep the substitution of the increments, but omit the part where it checks the application.
3. Omit the substitution of the increments. The user has the responsibility to use settings that are compatible with CoCoNuT (thus writing output at the correct times and being able to converge of course). This is mabye more elegant and versatile. If this solution is chosen, we could still try to extract the incrementation settings from the input file and compare them to the `delta_t` setting (which is used by the Fluent wrapper), just to raise a warning when there is a difference. Information on subcycling would then probably be omitted from the JSON-file, because it makes it longer and would also just serve as a check. Another question is then if we should apply this philosophy to other wrappers as well, becaues then we have a `delta_t` setting used by some wrappers but not all of them.

I would like to have a discussion about it before deciding on a solution, maybe there are more ideas to solve this or you all have a strong preference for one of the solutions.

**Comment by nicolasdlss** [comment]
The subcycling settings can be provided in different ways.
For example, the `maxInc` value (fourth) is optional and not automatically set when working with a `MODERATE DISSIPATION` step. On the other hand, a `STATIC` step does at it automatically.
This is just one example of how to incorporation of subcycling can lead to an excessive amount of programming and maintenance.
I would propose to keep the subcycling settings in the case setup (inp file).

**Comment by nicolasdlss** [comment]
From the CoCoNuT meeting of 5/7:
Only the time step should be overwritten, throwing a warning when the case value and the CoCoNuT value differ.
The subcycling settings should be part of the case file, not CoCoNuT.
