### ISSUE TITLE
Simplifying the predictors

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#54]
@nicolasdlss remarked that the predictors can be simplified. More specifically, the number of files can be reduced. 

We now have 6 predictor files & classes: base class, constant, linear, quadratic, cubic and legacy. 
This could be reduced to just one class, which has a single setting specifying the order of the predictor (0, 1, 2, 3). We could add a special setting for the legacy predictor, which can be used when comparing results with Tango. 
This would result in a bit less code in total, but most importantly in fewer files. 

Thoughts on this?

**Comment by joris13** [comment]
I would leave it like that. Now the name says what it does. They can become more complex if variable time stepping is included.
