### ISSUE TITLE
Improving restart

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#57]
Currently when restart is used, there is no derivative information (no modes from previous iterations for iqn-ils f.ex.), but more importantly, **as initial guess zero deformation is used**.

This makes the restart function useless in many practical cases with high added-mass, because the initial guess is too far from the actual solution (leading to a mode in iqn-ils, which is too 'wrong' to stabilize the coupling, resulting in divergence in the 3rd iteration). For example, performing five time steps for the tube_fluent2d_abaqus2d and then performing a restart will not work when using iqn-ils (fyi Aitken relaxation works but requires about 40 iterations per time step).

A simple and effective solution is to use the solution from the previous time step as initial guess. The implementation is straightforward, because the files from a previous time step are already there and the code to extract this displacement is there as well.

**Concretely, I suggest that for a restart, all solver wrappers store the values from the previous time step in the interface upon initialization.**

**Comment by nicolasdlss** [comment]
Instead of implementing this in the solver wrappers themselves, the predictor and model history can be save on the level of the coupled_solvers, avoiding an change in each solver wrapper.

**Comment by nicolasdlss** [comment]
Basically, the restart implementation just stores the predictor and model object as pickle file and loads them in upon restart.
Admittedly, the implemenation is therfore not the most storage efficient (you don't really need the whole object), but it has advantage of being fully incorporated in the coupled solvers and no other components need to be altered.
The parameter "save_restart" dictates how frequent the pickle file is stored:
0 : never
i (= 1, 2, ...) : every i time steps
-i (= -1, -2, ...) : every i time steps and only the last one is kept, older ones are removed

**Comment by joris13** [comment]
Great! Storage efficiency is not a concern here.
