### ISSUE TITLE
Equal method for Interfaces and ModelParts

### ISSUE THREAD

**Issue by nicolasdlss** [pyfsi/coconut#69]
Currently the equal method `__eq___(self, other)` of the Interface class checks equaltiy of model_part_variable_pairs and data.
It can be more useful to only check for the equality of model_part_variable_pairs. Additionally, it can be checked that the same model is referenced.
This can be useful in solver_wrappers and mappers.

**Comment by toondm** [comment]
[This post](https://dev.to/emadmokhtar/difference-between--and-is-in-python-and-when-to-use-each-of-them-357h) explains the different "equivalence" statements in Python, I think that's relevant to the discussion.
Summarized: `is` looks at the `id` (memory location), while `==` uses the `__eq__` function to check if the values are the same.

**Comment by nicolasdlss** [comment]
It would be useful to have a tool to compare model parts, therefore I propose an `__eq__` method in the `ModelPart` class which compares, name, x0, y0, zo and id.

Besides, it would be useful to have a tool to check whether interfaces have the same model parts, therefore I propose to have such a method either in the `Interface` class or in _`tools.py`_ with a name similar to `have_same_model_parts(...)`

**Comment by toondm** [comment]
> It would be useful to have a tool to compare model parts, therefore I propose an `__eq__` method in the `ModelPart` class which compares, name, x0, y0, zo and id.

Perhaps we can do this by comparing a hash that is calculated and stored during initialization? That avoids having to compare all ndarrays every time. 

> Besides, it would be useful to have a tool to check whether interfaces have the same model parts, therefore I propose to have such a method either in the `Interface` class or in _`tools.py`_ with a name similar to `have_same_model_parts(...)`

That might be useful, but just as a remark: does the order of `ModelParts` matter for this function/method? Because it does for the `Interface` read/write.

**Comment by nicolasdlss** [comment]
1 Hashing
I'm no expert and it seems quite complex, but from what I gather, hashes are not the way to go.
For example even for a dictionary, key lookups are always followed by an equality check. (hashes are not entirely unique) 
The opposite must be true however: hashable objects which compare equal must have the same hash value.
So it wouldn't make sense for our purpose to do this.

The following was also new to me:

>  By default, the __hash__() values of str and bytes objects are “salted” with an unpredictable random value. Although they remain constant within an individual Python process, they are not predictable between repeated invocations of Python.

Which might imply that there are problems when loading in pickle files from another Python run. But, as we never experienced this, it will probably be dealt with behind the scene.

https://hynek.me/articles/hashes-and-equality/
https://docs.python.org/3/library/functions.html#hash
https://docs.python.org/3/reference/datamodel.html#object.__hash__

2 Order of model parts
The order of the model parts needs to be equal indeed, and this is also how the `has_same_model_parts(...)` method is implemented. It is a good point, however, and I will add a check to the test.
