### ISSUE TITLE
Restructuring of tube examples

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#71]
The number of tube example cases is becoming quite high, as we have combinations of Python solvers, Fluent, OpenFOAM, Abaqus, Kratos, 2D and 3D. 
That means that e.g. the setup for the Fluent 2D case is saved several times, in different folders. 
Perhaps we could think of a more efficient way to organize this single example, where each solver wrapper has only one set of setup files, and many different combinations are possible, based on e.g. a folder of JSON files. 
Something to discuss after the new datastructure has been merged?

**Comment by navaneethkn** [comment]
I think it is a very good idea. We can put all the solver-specific input files in "tube_example_setup/<solver>".

**Comment by toondm** [comment]
When we restructure the tube example, we should also restructure the documentation about it, and more generally the documentation of the examples in general.

**Comment by nicolasdlss** [comment]
The prefix tube was indeed intended to make the distinction with other test cases. There is another issue about adding a new test case. So I would say yes...

Have you thought about `run_simulation.py`? This will probably also be copied.
And just an idea, maybe we could combine the  `setup_< solver >.sh` scripts to one `setup.sh` script for each example?
