### ISSUE TITLE
Add polynomials to radial basis mapping

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#77]
This issue concerns a possible extension/improvement of the current RBF mapper. 
By combing radial basis interpolation with polynomial interpolation, it should be possible to exactly recover rigid body motions. 
[This paper](https://www.sciencedirect.com/science/article/pii/S0965997817310906) gives more information about this technique.

**Comment by nicolasdlss** [comment]
There is also [a paper from Joris](https://www.sciencedirect.com/science/article/pii/S0045782512000862?via%3Dihub) which explains the technique briefly and [this one](https://www.sciencedirect.com/science/article/pii/S0045782513000029?via%3Dihub) is also an interesting one on this topic.
