### ISSUE TITLE
Fluent wrapper: read case and data file provided by user

### ISSUE THREAD

**Issue by hdolfen** [pyfsi/coconut#89]
Currently the Fluent wrapper reads in a case-file provided by the user and initializes it (for the initialization a setting is present in the JSON file). I think often a user benefits from having already a converged case to start from, which requires CoCoNuT to use the case and data file and without (re)initializing it. I propose to remove the initialization from CoCoNuT and make the user responsible for providing an initialized (or even solved) data-file.

**Comment by nicolasdlss** [comment]
Good remark!
Or we could make it optional: have a key in the JSON file "initialization" with possible values: hybrid, initialize-flow (or something similar) and None; None being the default?

**Comment by hdolfen** [comment]
> Good remark!
> Or we could make it optional: have a key in the JSON file "initialization" with possible values: hybrid, initialize-flow (or something similar) and None; None being the default?

That could indeed be done, but I don't really see the advantage of having CoCoNuT taking care of the initialization...
