### ISSUE TITLE
Speeding up operations with Interface objects

### ISSUE THREAD

**Issue by toondm** [pyfsi/coconut#9]
Currently the cost of the coupling algorithms (without the solver wrappers!) is mainly determined by the inefficient implementation of the `Interfaces`. Of course, the cost of the coupling algorithm is (usually) negligible with respect to that of the solvers, so this is not a pressing issue. However, I still think some redesign of the `Interface` class to boost performance here would be a good thing for the code. 

As illustration, I show here the cost of Interface operations, for an Interface with 10 000 DoFs:
![image](https://user-images.githubusercontent.com/52496830/78707868-80c4af80-7911-11ea-908b-b2d8709226cf.png)
The `deepcopy` function (which is also used in __add__) is clearly the bottleneck here, although the get and set functions are also quite slow. 

In an actual simulation with 10 000 DoFs, this results in the following time spent on different stuff during the coupling:
![image](https://user-images.githubusercontent.com/52496830/78708095-db5e0b80-7911-11ea-9409-8236c2d3886d.png)

This shows that most of the overhead can be avoided by not adding and subtracting with `Interfaces` but with ndarrays. However, `SetNumpyArray` is still a lot slower than all of the linear algebra together (includes `numpy.linalg.qr` and `scipy.linalg.solve_triangular`).

I think storing data in ndarrays would be much more efficient. However, as `Interfaces` are only references to `ModelParts`, that would require really big changes to the whole `data_structure` of CoCoNuT, so perhaps that is too extreme.

Anyway, this is something we should think of and discuss somewhere in the future in my opinion.

**Comment by nicolasdlss** [comment]
In my opinion, rewriting the `deepcopy` method could already mean a big win without requiring any changes to the datastructure.

This deepcopy method is called in practically every operation with `Interfaces` and is the main bottleneck, as such a speed-up would mean an important win. This `deepcopy` mehtod actually occupies middle ground between a shallow copy and a real deepcopy. The former being a copy of the collection structure, not the elements. With a shallow copy, two collections now share the individual elements. Whereas deep copies duplicate everything. A deep copy of a collection is two collections with all of the elements in the original collection duplicated.

Here, the `interfaces`  have to copied up to a certain level, as for instance global variables should not be copied. The way this is now implemented is by performing a thorough deecopy afterwhich the unwanted duplicated elements are switched with the original ones.  This is rather inefficient and in my opinion a large gain could be achieved by just copying what is needed. The python `deepcopy` method allows for just that by overriding certain methods. However, a bit of digging into the code and the documentation is required.

I think that rewriting the data structure is a bit too extreme for now as the inefficiency is minor with respect to the solvers as you pointed out.

**Comment by joris13** [comment]
I fully agree that there are inefficiencies below the hood and it is very good that they are illustrated with numbers and that possible solutions are proposed. However, at this moment we have to focus on finishing the PhDs and masters in their last stage. Efforts like this should be postponed at least until we have a physical meeting.

Best regards,
Joris

**Comment by toondm** [comment]
I'll start thinking of an improved datastructure with @navaneethkn and @nicolasdlss, so that we can propose this to the rest of the team in a couple of weeks.

**Comment by toondm** [comment]
Resolved issue by introducing new datastructure.
